<?php
namespace includes\posttypes;

use includes\classes\PostType;

class PostTypeEvents extends PostType {
    static $class = 'EventsPostType';
    public function getName() {
        return 'events';
    }
    public function getConfigs() {
        $name = $this->getName();
        $labels = array(
            'name'               => _x( 'Events', 'post type general name', 'dm' ),
            'singular_name'      => _x( 'Events', 'post type singular name', 'dm' ),
            'menu_name'          => _x( 'Eventss', 'admin menu', 'dm' ),
            'name_admin_bar'     => _x( 'Events', 'add new on admin bar', 'dm' ),
            'add_new'            => _x( 'Add New', 'book', 'dm' ),
            'add_new_item'       => __( 'Add New Events', 'dm' ),
            'new_item'           => __( 'New Events', 'dm' ),
            'edit_item'          => __( 'Edit Events', 'dm' ),
            'view_item'          => __( 'View Events', 'dm' ),
            'all_items'          => __( 'All Eventss', 'dm' ),
            'search_items'       => __( 'Search Eventss', 'dm' ),
            'parent_item_colon'  => __( 'Parent Eventss:', 'dm' ),
            'not_found'          => __( 'No projects found.', 'dm' ),
            'not_found_in_trash' => __( 'No projects found in Trash.', 'dm' )
        );
        $args = array(
            'labels'             => $labels,
            'description'        => __( 'Description.', 'dm' ),
            'public'             => true,
            'publicly_queryable' => true,
            'show_ui'            => true,
            'show_in_menu'       => true,
            'query_var'          => true,
            'rewrite'            => array( 'slug' => $name ),
            'capability_type'    => 'post',
            'has_archive'        => true,
            'hierarchical'       => false,
            'menu_position'      => null,
            'supports'           => array( 'title', 'editor', 'thumbnail'),
            'taxonomies' => array('post_tag')
        );

        return array_merge(parent::getConfigs(), $args); // TODO: Change the autogenerated stub
    }
}